### ISSUE TITLE
Bags outside of screen

### ISSUE THREAD

**Issue by henriksultan** [jaredbwasserman/Drift#1]
My bags wont show, seems to be outside of screen.

**Comment by jaredbwasserman** [comment]
Hi @henriksultan - thanks for the reporting this issue!  I could use some more information to help me figure out what is going wrong.

Is the issue occurring in retail or classic?

Did the bags stop showing recently, or did they never show up after installing the addon?

Could you attach your "Drift.lua" file located in the "SavedVariables" directory? It should be located in "C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\<account name>\SavedVariables" for retail or "C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\<account name>\SavedVariables" for classic. This file stores all the positions of the frames, so I want to take a look and see if anything looks incorrect.

Thanks!

**Comment by henriksultan** [comment]
o7 Sorry for the lack of information from start!

Retail version and the bags have never showed since installing and activating the addon. Dont have any other addon affecting the bags either. Use to have scrap but its gone, same issue. Tried deactivating Improved Blizzard UI to see if that had something to do with it and so on.
[Drift.zip](https://github.com/jaredbwasserman/Drift/files/4515931/Drift.zip)

Thanks for a quick reply and great addon btw ^^

**Comment by jaredbwasserman** [comment]
Thanks for the extra information!  I'll look into it when I have some time.

**Comment by jaredbwasserman** [comment]
I am able to repro the issue.  I'm working on a fix.

**Comment by jaredbwasserman** [comment]
@henriksultan I pushed a fix for the issue. Can you confirm you are able to see bags now?

**Comment by henriksultan** [comment]
Working like a charm man :)
