### ISSUE TITLE
Isn'an Issue of Feature Request but a Question only

### ISSUE THREAD

**Issue by Galthariel** [jaredbwasserman/Drift#10]
Does Drift saves windows positions/size between sessions? Also it's Account Wide or do I need to do it for every character? Thanks

**Comment by jaredbwasserman** [comment]
Hi @Galthariel - good questions! Yes, Drift saves window positions and sizes between sessions. After you log out and back in again, the windows will re-open in the positions you left them in with the sizes you adjusted them to. Yes, the window positions and sizes are Account Wide; all characters share the same window positions and sizes.

Please feel free to re-open if you have any more questions!

**Comment by Galthariel** [comment]
I'm not only good but happy with your replies. Installing it NOW. Thanks a lot :-)
