### ISSUE TITLE
Add BNToastFrame support

### ISSUE THREAD

**Issue by jaredbwasserman** [jaredbwasserman/Drift#14]
Add support for BNToastFrame.

**Comment by Galthariel** [comment]
When and if you decided to do this enhancement please make sure to do the same with the Quick Join Toast 1 and 2. Another that will be cool is called Battleground Score (I think it's the name) since my top bar covers it all the time 👍 
Thanks a bunch :-)

**Comment by jaredbwasserman** [comment]
Hi, Galthariel. I'm not sure which frame you mean by "Battleground Score." Drift already supports both the PVP Scoreboard and the PVP Results frames. Could you attach a screenshot or provide some further clarification about this frame?

Thanks!

**Comment by Galthariel** [comment]
Hi Jared,

Is the one that stays in the middle and top of the screen with Alliance and Horde Scores (e.g. Battle for Nazjatar). I tried to move the other day and did not let me but I may have done something wrong.

**Comment by jaredbwasserman** [comment]
Thanks for the clarification, Galthariel. I think I know which frame you mean. It seems to be called "UIWidgetTopCenterContainerFrame," and this frame is not currently supported by Drift.

Just to double check, I attached a screenshot of the score in Eye of the Storm that seems to be the same frame. Can you confirm?
![battlegroundscore](https://user-images.githubusercontent.com/5832654/96674419-9df52480-131d-11eb-8113-3d805c83d76e.jpg)

**Comment by Galthariel** [comment]
That's the one. I'm sorry for not provide you the screenshot before however I need to be doing PVP to see it. And basically the only PVP I do lately is the Battle for Nazjatar and I have not done yet any this week. Thanks and I'm sorry again

**Comment by jaredbwasserman** [comment]
No problem! Thanks for the clarification.

**Comment by jaredbwasserman** [comment]
Hi @Galthariel - I added support for BNToastFrame and Battleground Score in the latest version of Drift (1.0.6) that can be downloaded here https://www.curseforge.com/wow/addons/drift. I'm not sure if the BNToastFrame covers Quick Join Toast 1 and 2, could you help me confirm if they can be moved? I'm not sure if they are part of that frame or something else.

Thanks!

**Comment by jaredbwasserman** [comment]
I added Quick Join Toast 1 and Quick Join Toast 2 in the latest version of Drift (1.0.7) that can be downloaded here https://www.curseforge.com/wow/addons/drift. Please re-open this ticket if you run into any issues with Battle.net Toast Frame, Quick Join Toast 1 and Quick Join Toast 2, or Battleground Score.
