### ISSUE TITLE
Feature Request - Garrison Button

### ISSUE THREAD

**Issue by IHardes** [jaredbwasserman/Drift#17]
Hey, really nice addon would it be possible to add the Garrison Button to the moveable frames? 

Edit: I mean the retail version :)

Thanks
Steven

**Comment by jaredbwasserman** [comment]
Hi, Steven. Thanks for the suggestion! I want to make sure I know the frame you are referring to. Is it the one in the attached screenshot, or is it a different frame?

Thanks!
![garrisonbutton](https://user-images.githubusercontent.com/5832654/96674560-ef9daf00-131d-11eb-98b2-0e0604153db4.jpg)

**Comment by IHardes** [comment]
I mean the button at the Minimap that opens the garrison/order hall menu. I quess its called GarrisonLandingPageMinimapButton.
![image](https://user-images.githubusercontent.com/61800972/96724265-ed843080-13af-11eb-9f9c-4d28cd668482.png).

**Comment by jaredbwasserman** [comment]
Ah I see, thanks for the clarification!

**Comment by jaredbwasserman** [comment]
Hi, @IHardes - I added support for the Garrison button in the latest version of Drift (1.0.6). Please download it here https://www.curseforge.com/wow/addons/drift. Feel free to reopen this ticket if you run into any issues.

Thanks!
