### ISSUE TITLE
Extra Action Button resets after reload

### ISSUE THREAD

**Issue by class2u** [jaredbwasserman/Drift#18]
Hi, thank you for making this gerat addon. 👍 
The Extra Action Button is moveable but it resets position after UI reload. I test with Garrison Ability Button.
I notice that MoveAnything changes the frame name to ExtraAbilityContainer and removes ZoneAbilityFrame as well in new release. Don't know if it helps.

**Comment by jaredbwasserman** [comment]
Hi, Alex. Thanks for letting me know! The information about MoveAnything is very helpful. I'm working on a fix!

**Comment by jaredbwasserman** [comment]
Hi again, Alex. This bug should be fixed in the latest version of Drift (1.0.6) that can be downloaded here https://www.curseforge.com/wow/addons/drift. Could you download this new release and confirm the bug is no longer present?

Thanks!

**Comment by class2u** [comment]
Yes, I just confirmed that this issue has been fixed. Thank you!
