### ISSUE TITLE
Scale & Reset

### ISSUE THREAD

**Issue by class2u** [jaredbwasserman/Drift#2]
Thank you for making this great addon. I love it can save the position and fading out a little while moving. I have two feature requests: Scale the frame (and save the size) and reset frame position and szie.

**Comment by jaredbwasserman** [comment]
Hi @class2u - thanks for the feedback!  I agree that scaling and resetting would be super useful.  I'm planning to add these features at some point in the future.

**Comment by class2u** [comment]
Awesome! Thank you again.

**Comment by jaredbwasserman** [comment]
Scaling frames and resetting frame positions and sizes have both been added. To scale a frame, right-click and drag up or down. To reset frame positions and sizes, use the Reset Frames button in Drift's Interface Options (Game Menu -> Interface -> AddOns tab -> expand the Drift section -> General Options -> Reset Frames button).
