### ISSUE TITLE
Adventure Guide Dragging Broke Window

### ISSUE THREAD

**Issue by dotdissent** [jaredbwasserman/Drift#20]
The Adventure Guide was open and near the center of my screen. I had just navigated back to the Suggested Content page from the Dungeons page, scrolled through the content suggestion on the left with my mouse wheel, then attempted clicking and dragging from the bottom of the window to move it. It immediately went transparent and snapped to the left side of the screen in a higher location. The window stopped showing all text and BugSack began gathering rapid errors. A UI reload was enough to make it usable but not movable and not without the same error being thrown repeatedly. I was forced to /driftreset to resolve it and I could not reproduce it with the steps above.

----

103x Drift\DriftHelpers.lua:230: Usage: EncounterJournal:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
[string "=[C]"]: in function `SetPoint'
[string "@Drift\DriftHelpers.lua"]:230: in function <Drift\DriftHelpers.lua:204>
[string "@Drift\DriftHelpers.lua"]:270: in function <Drift\DriftHelpers.lua:269>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2910: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2755: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2623: in function <FrameXML\UIParent.lua:2619>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3468: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:3429: in function `ToggleFrame'
[string "@FrameXML\UIParent.lua"]:1052: in function `ToggleEncounterJournal'
[string "TOGGLEENCOUNTERJOURNAL"]:1: in function <[string "TOGGLEENCOUNTERJOURNAL"]:1>

Locals:
(*temporary) = EncounterJournal {
 0 = <userdata>
 TitleText = EncounterJournalTitleText {
 }
 searchBox = EncounterJournalSearchBox {
 }
 DriftModifiable = true
 SetPortraitShown = <function> defined @SharedXML\PortraitFrame.lua:52
 searchResults = EncounterJournalSearchResults {
 }
 SetPortraitTexCoord = <function> defined @SharedXML\PortraitFrame.lua:48
 SetPortraitTextureRaw = <function> defined @SharedXML\PortraitFrame.lua:40
 TitleBg = <unnamed> {
 }
 LootJournal = <unnamed> {
 }
 SetTitleMaxLinesAndHeight = <function> defined @SharedXML\PortraitFrame.lua:68
 SetTitleColor = <function> defined @SharedXML\PortraitFrame.lua:56
 suggestFrame = EncounterJournalSuggestFrame {
 }
 overviewDefaultRole = "DAMAGER"
 SetTitle = <function> defined @SharedXML\PortraitFrame.lua:60
 encounter = EncounterJournalEncounterFrame {
 }
 SetBorder = <function> defined @SharedXML\PortraitFrame.lua:27
 layoutType = "PortraitFrameTemplate"
 creatureDisplayID = 0
 DriftIsScaling = false
 SetPortraitAtlasRaw = <function> defined @SharedXML\PortraitFrame.lua:44
 SetPortraitToUnit = <function> defined @SharedXML\PortraitFrame.lua:36
 DriftIsMoving = false
 Bg = EncounterJournalBg {
 }
 SetTitleFormatted = <function> defined @SharedXML\PortraitFrame.lua:64
 NineSlice = <unnamed> {
 }
 TopTileStreaks = <unnamed> {
 }
 instanceSelect = EncounterJournalInstanceSelect {
 }
 SetPortraitToAsset = <function> defined @SharedXML\PortraitFrame.lua:32
 instanceID = 1185
 CloseButton = EncounterJournalCloseButton {
 }
 DriftSticky = true
 portrait = EncounterJournalPortrait {
 }
 navBar = EncounterJournalNavBar {
 }
 queuedPortraitUpdate = false
 selectedTab = 1
 inset = EncounterJournalInset {
 }
}
(*temporary) = nil
(*temporary) = "UIParent"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil

**Comment by jaredbwasserman** [comment]
Thank you for the detailed bug report! I will look into this when I get some time.

**Comment by jaredbwasserman** [comment]
@dotdissent - My guess based on reading through the error message is Drift saved an invalid position for the Adventure Guide, and when Drift tried to reset the Adventure Guide's position, the game threw errors because Drift tried to set the Adventure Guide to an invalid position. I'm not sure what could cause this issue.

Unfortunately, I'm not able to reproduce the issue given the steps above. You mentioned you were also unable to reproduce the issue. Have you encountered it more than once, or has it only happened one time?

**Comment by jaredbwasserman** [comment]
I added some logic in the latest release of Drift (1.0.9) to verify position values it saves are not nil. I am hoping this fixes the bug. Please re-open this ticket if you see the bug again. Thanks!
