### ISSUE TITLE
Feature request - Minimap

### ISSUE THREAD

**Issue by johanruda** [jaredbwasserman/drift#22]
Any possibility we could have the minimap movable?
I'm playing on an ultrawide monitor and it's so far to the right... 😅

**Comment by jaredbwasserman** [comment]
Hey @johanruda - I'll look into it. I think it should be doable.

**Comment by jaredbwasserman** [comment]
@johanruda It turns out it's much more difficult to move the minimap in retail than in classic. Do you primarily play retail or classic (or both)?

**Comment by johanruda** [comment]
I play both, but primarily classic TBC

Den ons 23 juni 2021 kl 10:06 skrev Jared Wasserman <
***@***.***>:

**Comment by jaredbwasserman** [comment]
I'm testing the Minimap functionality. It seems to work in retail and classic. I'll probably release the update in the next few days.

**Comment by johanruda** [comment]
Fantastic! Thank you! :)
One more thing, the gem socketing window. You want me to make another request for that one?

**Comment by jaredbwasserman** [comment]
The socket window should be movable. Are you unable to move it?

This is the frame you are referring to, right?
![WoWScrnShot_063021_003430](https://user-images.githubusercontent.com/5832654/123920829-362abb00-d93b-11eb-9553-87b0f92cc0bf.jpg)

**Comment by johanruda** [comment]
That is the frame, yes, but on TBC Classic. Double-checked just now and I can't move it.

**Comment by jaredbwasserman** [comment]
Ah I see, I was thinking retail. Thanks for the clarification. I haven't added it yet for TBC. Can you create a separate request for socket frame in TBC?

**Comment by jaredbwasserman** [comment]
I just added Minimap in v1.0.14. Closing this out.
