### ISSUE TITLE
transmog frame

### ISSUE THREAD

**Issue by lenoirrichelieu** [jaredbwasserman/drift#26]
Hi,
I found a bug related to the transmogrification window. When I open it (true, from Grand Expedition Yak) I have a separate background left which doesn't disappear after closing the window. 

![image](https://user-images.githubusercontent.com/94080045/142754864-a9555fb4-8356-4a40-9ab3-3ee5196f391a.png)

When I disable Drift the bug disappears. I tried with "miscellaneous" option unchecked but the bug persisted. Unfortunately there is no error popping up. I think is related to Drift because I checked with every addon on and off which may interfere in anyway with such frames (and I don't have UI modifiers like ElvUi or Skinner or anything like that).

I will see if this appears when visiting the transmog guy instead of mount derived frame.

**Comment by jaredbwasserman** [comment]
Hi @lenoirrichelieu - Thanks for the bug report and detail! You're correct that it's related to Drift. I recently implemented a workaround for Collections, and this looks like it's related. I can reproduce the issue, and I will work on a fix.

**Comment by jaredbwasserman** [comment]
@lenoirrichelieu - This should be fixed in Drift v1.0.21. Can you download the update and let me know if the issue is fixed on your end? Thanks!

**Comment by lenoirrichelieu** [comment]
@jaredbwasserman - It is fixed. I checked on multiple chars with and without other addons enabled. I consider this issue closed.

**Comment by jaredbwasserman** [comment]
Thanks for confirming!
