### ISSUE TITLE
Lua error when enable friendly nameplates in raid

### ISSUE THREAD

**Issue by class2u** [jaredbwasserman/drift#29]
Hi, 
Thank you for making this great addon. I get the following Lua error message when enable friendly nameplates inside the raid instance Sepulcher of the First Ones. This is happening after Hotfix in 22th March. I am using Drift v1.0.25-retail. The raid need to be larger then 25 people maybe.

22844x FrameXML\CompactUnitFrame.lua:1122: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `Hide'
[string "@FrameXML\CompactUnitFrame.lua"]:1122: in function `CompactUnitFrame_UpdateClassificationIndicator'
[string "@FrameXML\CompactUnitFrame.lua"]:1380: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}

**Comment by jaredbwasserman** [comment]
Hi @class2u - Thanks for reporting this bug and the details! I attempted to reproduce the issue by enabling friendly nameplates inside of a 25 man Sepulcher of the First Ones. I also attempted to reproduce the issue by enabling friendly nameplates in a raid group larger than 25 people for a world boss. In both cases, I was unable to reproduce the issue.

Drift does not modify nameplates at all, so I am not sure how this interaction could occur. Is it possible you have any other AddOns installed that could be causing this issue? Additionally, could you test whether this issue still occurs while Drift is disabled?

**Comment by class2u** [comment]
Thank you for replying and testing. Last time I tested it with Drift, EaseAddonController, BugGrabber, BugSack, Ace3 and some shared libs. I did not get this Lua error after disabling Drift and keeping the others enabled. 

I will test it again with Drift only when I am in raid.

**Comment by class2u** [comment]
I tested with Drift only. Disabled all other addons. When enabling friendly nameplates in a 25 player raid, I got the same Lua error message. BTW, I am using zh-TW game client. Thank you.

**Comment by jaredbwasserman** [comment]
Thanks for the additional testing and detail! I was able to reproduce the issue exactly as you have described. I am not sure why the error did not show up for me the first couple times I tested but did show up for me this time. I am also not sure the exact cause of the error. It will take me some time to investigate.

**Comment by jaredbwasserman** [comment]
Attaching a taint log here for my own reference.
[taint.log](https://github.com/jaredbwasserman/drift/files/8502214/taint.log)

**Comment by jaredbwasserman** [comment]
Attaching another taint log for reference.
[taint2.log](https://github.com/jaredbwasserman/drift/files/8504095/taint2.log)

**Comment by jaredbwasserman** [comment]
Third taint log for reference.
[taint3.log](https://github.com/jaredbwasserman/drift/files/8504422/taint3.log)

**Comment by jaredbwasserman** [comment]
These issues look like they could be the same bug:
https://github.com/Auctionator/Auctionator/issues/1133
https://github.com/Auctionator/Auctionator/issues/1136

**Comment by jaredbwasserman** [comment]
This seems to have fixed the issue for Auctionator: https://github.com/Auctionator/Auctionator/commit/f59e54f2d41da0355d5666fd65fce3ef9d8e5ef2

**Comment by jaredbwasserman** [comment]
This could be related too https://github.com/jordonwow/bigdebuffs/issues/367

**Comment by jaredbwasserman** [comment]
These all look like the same issue too:
https://us.forums.blizzard.com/en/wow/t/uknown-ui-error/1221765
https://us.forums.blizzard.com/en/wow/t/ui-error-while-fighting-prototype-pantheon/1220618
https://us.forums.blizzard.com/en/wow/t/ui-error-while-fighting-prototype-pantheon/1220619
https://us.forums.blizzard.com/en/wow/t/lua-error-not-caused-by-addon/1210295/4

**Comment by jaredbwasserman** [comment]
Hi @class2u - I was able to fix the bug on my end. It appears to have been caused by using dropdowns in the addon interface options. Can you use the attached version of Drift and let me know if it fixes the bug for you when enabling friendly nameplates inside the raid instance Sepulcher of the First Ones? Thanks!
[drift-v1.0.25-retail.zip](https://github.com/jaredbwasserman/drift/files/8727283/drift-v1.0.25-retail.zip)

**Comment by class2u** [comment]
This is a great news! I have downloaded and will test it later.
