### ISSUE TITLE
Feature Request - Movable Bags

### ISSUE THREAD

**Issue by webdevdave** [jaredbwasserman/Drift#3]
Heya, love the addon but one of the things that I would love to see added are the inventory and bank bags. I don't like to use bag addons, but I do hate the position the bags come up naturally. Do you think you could include bags as part of the movable frames?

Thanks!
Dave

**Comment by webdevdave** [comment]
Oh and I'm talking about for Retail. Thanks again!

**Comment by jaredbwasserman** [comment]
Hi @webdevdave - thanks for the suggestion! I definitely agree it would be a great improvement to have movable inventory and bank bags. I actually had this feature in a previous version of the addon (retail and classic), but it caused some nasty Lua errors with the base game's interface code. I took support for moving bags out of the addon to avoid these errors; however, I will definitely consider adding support back in the future!

**Comment by webdevdave** [comment]
Would be awesome if you could get it working! I'm currently using an addon called OpenContainer https://www.wowinterface.com/downloads/info12435-OpenContainer.html which seems to work ok (maybe you can peek at its code for ideas?), but it breaks with ElvUI https://ibb.co/sFGNSBC so I actually stopped using ElvUI just because I hate not having movable bags lol. Fingers crossed! 🤞

**Comment by jaredbwasserman** [comment]
Cool, thanks for the information! I'll take a look at OpenContainer and try to get Drift movable bags working and compatible with ElvUI.

**Comment by jaredbwasserman** [comment]
Hi @webdevdave - I just added support for movable bags! Can you download the latest version of addon (https://www.curseforge.com/wow/addons/drift) and let me know if it works for you?

I was able to get movable bags working with ElvUI by disabling the ElvUI bag support.
![elvuibags](https://user-images.githubusercontent.com/5832654/89728652-b2df3e80-d9e3-11ea-8d01-71bcf5bf9d87.jpg)

**Comment by webdevdave** [comment]
Dude! You did it! You're the best! I also love that you can scale frames, I always felt my dressing room window was too small when I wanted to check out transmog stuff... now it's nice and big! Now you just have to promise to keep the addon updated and never abandon it! :) Thanks, man! ❤❤❤😜
