### ISSUE TITLE
Trying to Join a Community

### ISSUE THREAD

**Issue by webdevdave** [jaredbwasserman/drift#30]
![Screenshot 2022-06-01 140111](https://user-images.githubusercontent.com/56913415/171472295-e5c9e022-13da-4dbc-ba3c-43fbdc6a57e7.png)

So, whenever I am invited to a community in WoW, I would hear a noise like a window opened, but wouldn't see anything. After disabling ElvUI (I thought that might be the culprit) and trying again, this window popped up. Upon hitting "Disable" the community window worked. So, I'm hoping you can fix this.

Thanks, and keep up the great work!!!!! :)

**Comment by jaredbwasserman** [comment]
Hi @webdevdave - Thank you for letting me know about this bug and providing repro steps! I will investigate.

**Comment by jaredbwasserman** [comment]
I was able to reproduce the issue by clicking a join community link. Posting the output from BugGrabber here.
```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Drift' tried to call the protected function 'GetLastTicketResponse()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GetLastTicketResponse'
[string "@Blizzard_Communities\CommunitiesHyperlink.lua"]:10: in function <Blizzard_Communities\CommunitiesHyperlink.lua:7>
```

**Comment by webdevdave** [comment]
Nice, I'm glad you were able to figure it out. Hope to see an update soon!!! :)

**Comment by jaredbwasserman** [comment]
Good news! I was able to fix the issue on my machine. @webdevdave - Can you try this attached version of Drift and let me know if it fixes the issue for you as well?
[drift-v1.1.0-retail.zip](https://github.com/jaredbwasserman/drift/files/8841392/drift-v1.1.0-retail.zip)

**Comment by webdevdave** [comment]
Hey, so sorry that I took so long to get back to you!!! So, it seems that Drift is working now. When I had my friend help me test it by inviting me to his community a few times, Drift never came up with the error. Two other addons did, but I assume you wouldn't know what I could do to fix them. Them being
AddOnSkins
BetterWardrobe
If there is some sort of small hack I could try on them that you know of though, I'd love to give it a go. Otherwise, thanks again for maintaining Drift - it's a fantastic addon! :)

**Comment by jaredbwasserman** [comment]
Thanks for confirming Drift is working!

Unfortunately, I am not aware of any workarounds other than modifying the code of the addons themselves. I recommend disabling all addons except the one you are testing (e.g. AddOnSkins or BetterWardrobe), turning on the taint log ( https://wowpedia.fandom.com/wiki/CVar_taintLog ), and then seeing what the taint log shows after you click a link. It is possible these addons are insecurely hooking a function (that is what Drift was doing prior to this update), and the taint log could reveal more information. If the taint log does provide useful information, I recommend reaching out to the authors of these addons and providing the taint log output and repro steps.
