### ISSUE TITLE
Broken in 9.2.7

### ISSUE THREAD

**Issue by michel-bosseaux** [jaredbwasserman/drift#32]
Some of the windows cannot be dragged anymore since 9.2.7, like "Talking Heads".

**Comment by jaredbwasserman** [comment]
Thanks for letting me know! I will take a look.

**Comment by jaredbwasserman** [comment]
@michel-bosseaux - I have not noticed any issues with windows in 9.2.7. I am able to move the Talking Head frame fine. Do you have any other addons installed that may be interfering? Could you attach a screenshot of your addon settings for Drift (Interface -> Addons -> Drift)? Thanks!

**Comment by jaredbwasserman** [comment]
Closing this out since I cannot reproduce.
