### ISSUE TITLE
Support for WoWup

### ISSUE THREAD

**Issue by WybeBosch** [jaredbwasserman/drift#33]
Hey there! 
Would it be possible that you would modify your Zip File releases in such as way that WoWup can be used to install your addon? (They have support for synced updates via github url) 

Only thing that needs to be changed i think is some folder structure within your zipfile!

Documentation found here
[Folder structure](https://wowup.io/guide/wowup/hub)
[Install from URL using WoWUp](https://wowup.io/guide/get-addons/overview)

example repo made by WoWup:
https://github.com/WowUp/WowUp.Addon

"Basically just requires a zip with a directory in it named the same as the toc, with the addon in that directory, as you would have it in the Addons directory in your client."

If not, its also an option to release the addon on wago addons, they have support for the WoWup client by default, but still provide ad revenue.

**Comment by jaredbwasserman** [comment]
Hi! Thanks for the information! I will look into this when I have some time.

**Comment by WybeBosch** [comment]
Awesome, thanks for looking into it when you have time!

**Comment by jaredbwasserman** [comment]
I just added Drift to Wago ( https://addons.wago.io/addons/drift ), and I was able to install locally using WoWUp. Can you confirm you can install Drift using WoWUp as well?

**Comment by WybeBosch** [comment]
Very nice! Yes i can find the addon when using the WoWup client now under the Wago provider, and installing works succesfully aswel!
