### ISSUE TITLE
Broken as of patch 10.0

### ISSUE THREAD

**Issue by MrWizard516** [jaredbwasserman/drift#35]
Since the release of patch 10.0, it works but yet doesn't work. What I mean is that yes it works as intended but due to the changes in the UI for this patch, it prevents you from saving your UI changes through the new interface. Doing so merely saves some changes not all. However, disabling the addon allows you to save and restore all custom changes.

**Comment by webdevdave** [comment]
Hoping to have Drift back in shape soon! One of my favorite addons. No other UI Move addon can compete!

**Comment by jaredbwasserman** [comment]
Thanks for letting me know. I am working on a fix.

**Comment by jaredbwasserman** [comment]
This should be fixed in the latest version of Drift (v2.0.0). Please re-open if you're still experiencing issues.
