### ISSUE TITLE
Breaking WOTLK version

### ISSUE THREAD

**Issue by Mard35** [jaredbwasserman/drift#36]
"Remove support for minimap, objectives, bags, arena"
Why did you do that for WOTLK version???? Are you kidding?
WHY are you making updates for retail which breaking the wotlk version? It's so dumb! Don't touch it please, just don't!

**Comment by drixlow** [comment]
Yeah not too sure in the logic behind this latest update, sticking with v1.2.0 is likely the best bet at this point.

**Comment by jaredbwasserman** [comment]
Good point. I was going for consistency, but considering the games are different, it makes sense to leave in the existing functionality for classic and Wrath classic. I will add those frames back.

**Comment by jaredbwasserman** [comment]
I restored minimap, objectives, bags functionality in v2.1.0. The ArenaFrame was retail only, so v2.1.0 will have all the previous functionality plus a couple bug fixes.
