### ISSUE TITLE
Bags Not Movable

### ISSUE THREAD

**Issue by webdevdave** [jaredbwasserman/drift#37]
Hey man!
If you remember me, I'm the guy who has always been so happy that you've managed to make bags movable. Well, it seems with your recent update I'm unable to move them. Hoping you can add it back in! It was my favorite feature of Drift! 🤞

Thanks!!!

**Comment by jaredbwasserman** [comment]
Hi @webdevdave - Thanks for letting me know. Given the recent UI update in retail, I need to rethink how to implement Bags. I'll look into this when I get some time.

**Comment by webdevdave** [comment]
I wonder what their deal with bags is? I really expected them to be movable in the new UI design they just put out (I believe you mentioned you used to work at Blizz... any insight?). But thanks, hopefully you can figure it out!

**Comment by halloaloe** [comment]
Popped in to 2nd the comment: I love Drift for the ability to move bags around. I was hoping Blizz would make that option available with their new UI, but since no dice, I continue to rely upon your wonderful addon. Please please please make that function available again.

**Comment by jaredbwasserman** [comment]
Bags restored in Drift v2.1.0. Enjoy!

**Comment by webdevdave** [comment]
> Bags restored in Drift v2.1.0. Enjoy!

You da man! Downloading now! Thank youuuuuu! <3
