### ISSUE TITLE
Make VehicleSeatIndicator and DurabilityFrame moveable

### ISSUE THREAD

**Issue by Aur0r4** [jaredbwasserman/drift#38]
Hello,

I was coming over here from MoveAnything. I really like Drift so far, the only thing that I'm missing right know is the ability to move the Vehicle Seat Indicator and the durability figure.

Any chance that you can implement that?

![image](https://user-images.githubusercontent.com/28149249/199815107-31252f7b-e899-47c0-90e3-efa896eb9ae9.png)

cheers,
Aur0r4

**Comment by jaredbwasserman** [comment]
Hi @Aur0r4 - Yes, this should be possible.

**Comment by Aur0r4** [comment]
Thank you!

**Comment by Aur0r4** [comment]
You could also add "PlayerPowerBarAlt":

![image](https://user-images.githubusercontent.com/28149249/200664413-74da0a04-3649-4f0d-8a8b-3fad0e1e8e14.png)

I've added it manually and it seems to work fine so far but I'm not sure if this is the same-bar that appears in some bossfights.

**Comment by jaredbwasserman** [comment]
It looks like PlayerPowerBarAlt is tied to EncounterBar now, so you should be able to move PlayerPowerBarAlt by using Edit Mode and moving Encounter Bar.

**Comment by jaredbwasserman** [comment]
I added VehicleSeatIndicator and DurabilityFrame in Drift v2.2.0. They are both in the "Miscellaneous" category.
