### ISSUE TITLE
Mail Windows

### ISSUE THREAD

**Issue by webdevdave** [jaredbwasserman/drift#39]
Using ElvUI so not sure if that has any bearing... but when I open my mailbox, the **Inbox/Send** windows are not movable. When I try and move it it kinda freaks out, goes blank, and then all the text in it disappears. Here are before/after screenshots of trying to drag the inbox...

BEFORE:
<img src="https://i.ibb.co/pL7Lf9x/before.png" alt="before" border="0">

AFTER:
<img src="https://i.ibb.co/n6L6bx4/after.png" alt="after" border="0">

Hope that helps!

**Comment by jaredbwasserman** [comment]
Hi @webdevdave - Thanks for letting me know. My guess is it is likely related to ElvUI. I will need to investigate further.

**Comment by jaredbwasserman** [comment]
This is fixed in Drift v2.1.1.
