### ISSUE TITLE
Open All Bags

### ISSUE THREAD

**Issue by webdevdave** [jaredbwasserman/Drift#4]
I've got another feature request for you (yay!)... would be great to have options for bags to open automatically when you open your Bank or AH window. Similar to how [OpenContainer](https://www.wowinterface.com/downloads/info12435-OpenContainer.html) does it...
![opencontainer](https://user-images.githubusercontent.com/56913415/89924659-54c37e80-dbd0-11ea-8e07-c0d51814ae55.jpg)

Perhaps not quite as robust, but something to that effect.

Thanks again! :)

**Comment by jaredbwasserman** [comment]
Hi Dave, thanks for the suggestion!  This would be a really cool feature; however, I'm not sure it fits in with the rest of the addon. I would prefer to keep the scope of Drift as just allowing frames to move and resize, and this feels like added complexity. Just for my own understanding though, your reason for not using OpenContainer is that it is incompatible with ElvUI, right?

**Comment by webdevdave** [comment]
Thanks, Jared... I see your point! And yes, for some reason with ElvUI the bags go crazy and stretch all over the place like this...
![bags](https://user-images.githubusercontent.com/56913415/90066991-79952000-dcbc-11ea-8dcf-33a0a2f04db5.jpg)

But in OpenContainer you can disable dragging bags, so I just ended up combining your two addons by disabling the bag dragging in OpenContainer but using its auto-opening features... so it all worked out. It'd be cool if Drift did it just because I prefer to consolidate the number of addons I have where I can... but no biggy at all. I'm just glad your addon exists! :)

**Comment by jaredbwasserman** [comment]
Awesome, I'm glad you were able to find a solution! I'm going to close this out. Thanks, Dave.
