### ISSUE TITLE
Objective Tracker

### ISSUE THREAD

**Issue by Tyrsa78** [jaredbwasserman/drift#40]
Came here from Moveanything, love this addon sofar. Does everything I want but I'd love to be able to scale the Objective Tracker. The new Blizz Edit Mode allows it to move but I can't scale it down. The lettertype is too big for me, I'd like it smaller. Any chance you can make this possible? I play Retail.

**Comment by jaredbwasserman** [comment]
Yes, this should be possible.

**Comment by Tyrsa78** [comment]
Thank you so much! I appreciate your hard work.

**Comment by jaredbwasserman** [comment]
I added scaling support for the Objective Tracker in retail in Drift v2.2.0.
