### ISSUE TITLE
Drift vs Blizz Function?

### ISSUE THREAD

**Issue by halloaloe** [jaredbwasserman/drift#41]
When Drift is on, and all bags are open, I can't click to use items like the brew of the month bottle or a hearthstone; I get the error message that Drift is blocking a Blizz UI function and the option to ignore or disable. If the bag containing said items is solely open, then they work fine. When Drift is off, and I'm trying to open all bags at once (which doesn't happen, they all pile on top of one another), I'm then hit with this nonsense. Good luck:

7x Interface/FrameXML/ContainerFrame.lua:1201: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: ContainerFrame2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1201: in function `UpdateContainerFrameAnchors'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1125: in function `ContainerFrame_GenerateFrame'
[string "@Interface/FrameXML/ContainerFrame.lua"]:206: in function <Interface/FrameXML/ContainerFrame.lua:200>
[string "@Interface/FrameXML/ContainerFrame.lua"]:222: in function `OpenBag'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1961: in function `OpenAllBagsMatchingContext'
[string "@Interface/FrameXML/ItemUtil.lua"]:74: in function `OpenAndFilterBags'
[string "@Interface/AddOns/Blizzard_Soulbinds/Blizzard_SoulbindsViewer.lua"]:88: in function <...dOns/Blizzard_Soulbinds/Blizzard_SoulbindsViewer.lua:78>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2664: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3150: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_Soulbinds/Blizzard_SoulbindsViewer.lua"]:186: in function `OpenSoulbind'
[string "@Interface/AddOns/Blizzard_Soulbinds/Blizzard_SoulbindsViewer.lua"]:179: in function `Open'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:128: in function `showFunc'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:183: in function `ShowFrame'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:215: in function <Interface/FrameXML/PlayerInteractionFrameManager.lua:212>

Locals:
(*temporary) = ContainerFrame2 {
 0 = <userdata>
 CheckAuthenticatorSlotsHelpTip = <function> defined @Interface/FrameXML/ContainerFrame.lua:1055
 UpdateMoneyFrame = <function> defined @Interface/FrameXML/ContainerFrame.lua:730
 UpdateFilterIcon = <function> defined @Interface/FrameXML/ContainerFrame.lua:922
 GetTitleText = <function> defined @Interface/SharedXML/PortraitFrame.lua:28
 GetPaddingWidth = <function> defined @Interface/FrameXML/ContainerFrame.lua:849
 SetPortraitTexCoord = <function> defined @Interface/SharedXML/PortraitFrame.lua:87
 size = 32
 CheckUpdateDynamicContents = <function> defined @Interface/FrameXML/ContainerFrame.lua:822
 UpdateIfShown = <function> defined @Interface/FrameXML/ContainerFrame.lua:1036
 GetBagID = <function> defined @Interface/FrameXML/ContainerFrame.lua:746
 TitleContainer = Frame {
 }
 UpdateItemContextMatching = <function> defined @Interface/FrameXML/ContainerFrame.lua:1073
 LayoutAddSlots = <function> defined @Interface/FrameXML/ContainerFrame.lua:1081
 SetTitle = <function> defined @Interface/SharedXML/PortraitFrame.lua:36
 OnCloseClicked = <function> defined @Interface/FrameXML/ContainerFrame.lua:726
 PortraitButton = ContainerFrame2PortraitButton {
 }
 GetInitialItemAnchor = <function> defined @Interface/FrameXML/ContainerFrame.lua:863
 CalculateHeight = <function> defined @Interface/FrameXML/ContainerFrame.lua:833
 IsCombinedBagContainer = <function> defined @Interface/FrameXML/ContainerFrame.lua:574
 SetPortraitAtlasRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:83
 CancelRefresh = <function> defined @Interface/FrameXML/ContainerFrame.lua:963
 MatchesBagID = <function> defined @Interface/FrameXML/ContainerFrame.lua:754
 UpdateAddSlots = <function> defined @Interface/FrameXML/ContainerFrame.lua:1077
 IsExtended = <function> defined @Interface/FrameXML/ContainerFrame.lua:566
 SetTitleFormatted = <function> defined @Interface/SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 ClickableTitleFrame = Button {
 }
 CalculateWidth = <function> defined @Interface/FrameXML/ContainerFrame.lua:829
 SetPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:95
 Items = <table> {
 }
 GetRows = <function> defined @Interface/FrameXML/ContainerFrame.lua:790
 AddItemsForRefresh = <function> defined @Interface/FrameXML/ContainerFrame.lua:970
 SetPortraitShown = <function> defined @Interface/SharedXML/PortraitFrame.lua:91
 GetExtraRows = <function> defined @Interface/FrameXML/ContainerFrame.lua:782
 EnumerateValidItems = <function> defined @Interface/FrameXML/ContainerFrame.lua:598
 SetPortraitTextureRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:79
 GetBagSize = <function> defined @Interface/FrameXML/ContainerFrame.lua:554
 CalculateExtraHeight = <function> defined @Interface/FrameXML/ContainerFrame.lua:840
 SetTitleMaxLinesAndHeight = <function> defined @Interface/SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @Interface/SharedXML/PortraitFrame.lua:32
 FilterDropDown = ContainerFrame2FilterDropDown {
 }
 UpdateItems = <function> defined @Interface/FrameXML/ContainerFrame.lua:998
 UpdateSearchResults = <function> defined @Interface/FrameXML/ContainerFrame.lua:603
 FilterIcon = Button {
 }
 EnumerateItems = <function> defined @Interface/FrameXML/ContainerFrame.lua:586
 Background1Slot = ContainerFrame2Background1Slot {
 }
 GetPaddingHeight = <function> defined @Interface/FrameXML/ContainerFrame.lua:844
 CloseButton = Button {
 }
 UpdateFrameSize = <function> defined @Interface/FrameXML/ContainerFrame.lua:853
 Bg = Frame {
 }
 IsBackpack = <function> defined @Interface/FrameXML/ContainerFrame.lua:578
 onCloseCallback = <function> defined @Interface/FrameXML/ContainerFrame.lua:720
 SetBorder = <function> defined @Interface/SharedXML/PortraitFrame.lua:62
 layoutType = "HeldBagLayout"
 GetFirstButtonOffsetY = <function> defined @Interface/FrameXML/ContainerFrame.lua:770
 GetContainedBagIDs = <function> defined @Interface/FrameXML/ContainerFrame.lua:750
 CanUseForBagID = <function> defined @Interface/FrameX

**Comment by jaredbwasserman** [comment]
Hi @halloaloe - Thanks for the detailed bug report!
1. For the first issue, where Drift is blocking a UI function, that is definitely a bug. I will investigate and try to fix it.
2. For the second issue (`Action[SetPoint] failed...`) I have looked into this before and do not have a great solution at the moment. A workaround you can use to prevent the issue, though, is disable Bags in Drift prior to disabling the whole Drift addon. I put some cleanup code that triggers when Bags are disabled in Drift to prevent these errors. If Bags are enabled when Drift is turned off, the issue occurs, so Bags must be disabled prior to to turning off Drift. I am not aware of a way to get around this entirely, unfortunately.

**Comment by halloaloe** [comment]
Also noticing that when Drift is on, the backpack doesn't show up, whether opened by itself or with Shift B. I hear it open/close & see the indicator light on the icon, but it is just a blank spot where I've arranged my bags. I'm now having to turn off Drift to use my hearthstone (it's stored in the backpack) lol

**Comment by webdevdave** [comment]
Just came to report basically the same issue. When r-clicking items in my bags to use them, I get this popup...

![right-click-items-in-bags](https://user-images.githubusercontent.com/56913415/202875237-67da6905-5739-4958-bd31-fffb6531508a.png)

The main reason I love Drift so much more than similar addons is because its ability to position bags, so I'm really hoping you can get this fixed! I'm sick of using the ElvUI single bag (which let's me use items even though Drift is enabled). Thanks!!!

**Comment by jaredbwasserman** [comment]
I fixed all the bag issues in Drift v2.1.1. Also, I was able to make it so that disabling Drift no longer causes issues (no more need to disable Bags before disabling Drift altogether - Drift can be toggled on/off with Bags enabled). Please re-open this ticket if I missed something.
