### ISSUE TITLE
Drift Conflict with Shadowed Unit Frames

### ISSUE THREAD

**Issue by derekengel** [jaredbwasserman/drift#42]
I'm not sure if it's a conflict with Drift and Shadowed Unit Frames or Shadowed Unit Frames causing the problem.  When Shadowed Unite frames is enabled, I cannot single click any NPC or PC.  If I try to right click to turn my camera angle, it uses the resize option to resize my player frame.

**Comment by jaredbwasserman** [comment]
Interesting, there might be some hidden frames receiving clicks. I'll need to investigate further.

**Comment by BloodDragon2580** [comment]
I have the same problem

**Comment by BloodDragon2580** [comment]
I could find out that the bug with shadowunitframes is related to the scale option. If you remove the scaling at drift everything works without problems.

**Comment by jaredbwasserman** [comment]
There was a bug on the Drift side where it was mistakenly trying to scale the SUFWrapperFrame. I fixed this issue in Drift v2.2.0.
