### ISSUE TITLE
Since the patch on 11/15/2022 the addon doesn't seem to be working

### ISSUE THREAD

**Issue by cbcatanz** [jaredbwasserman/drift#43]
Like the title states, nothing seems to be working since the latest patch. I cannot move or resize anything. Also, I can't open my bags with the addon enabled.

**Comment by halloaloe** [comment]
Same here. Had to turn off the mod to silence the error messages

**Comment by Aur0r4** [comment]
The AddOn is working fine for me with 10.0.2 patch, have you guys tried to reset the AddOn profile in the SavedVariables folder?

**Comment by cbcatanz** [comment]
> The AddOn is working fine for me with 10.0.2 patch, have you guys tried to reset the AddOn profile in the SavedVariables folder?

Thanks for the suggestion. I tried that. The addon is still not working for me. I know the last patch broke a lot of addons. Hopefully, this one will get an update for the newest patch soon.

**Comment by jaredbwasserman** [comment]
@cbcatanz or @halloaloe - Can you provide a sample error message?

**Comment by halloaloe** [comment]
Ok: Drift is on, Bags Enabled. Had all bags open, adjusted to where I wanted them, and they were FULL. Tried to click on an item in the bottom right-hand corner of the Backpack itself. Got this:
21x [ADDON_ACTION_FORBIDDEN] AddOn 'Drift' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1384: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1435: in function <FrameXML/ContainerFrame.lua:1423>

Once I closed all bags, reopened the Backpack and just one other bag, moved the item I needed to use into a non-edge bag slot in the other bag and clicked it; it worked. No error message.
Will update with more if I get other errors. I've purposely kept Drift off for a while, so I'll see what pops up.

**Comment by Aur0r4** [comment]
I'm not the author and I may be wrong but isn't that error pointing to an BugGrabber function that is failing here? I would try to update BugGrabber and test again.

**Comment by halloaloe** [comment]
@Aur0r4 I have the most recent version of BugGrabber, which hasn't been updated itself since Nov. 14th.

**Comment by jaredbwasserman** [comment]
Thanks, everyone, for all this info. I fixed all the Bag-related issues I could find in Drift v2.1.1. Please re-open this ticket if there are still issues following the update.
