### ISSUE TITLE
Lua error when using Dragonriding Customization system

### ISSUE THREAD

**Issue by class2u** [jaredbwasserman/drift#45]
1x Interface/AddOns/Drift/DriftOptions.lua:405: attempt to index field 'objectivesEnabledCheckbox' (a nil value)
[string "@Interface/AddOns/Drift/DriftOptions.lua"]:405: in function <Interface/AddOns/Drift/DriftOptions.lua:362>
[string "=[C]"]: in function `Hide'
[string "@Interface/FrameXML/UIParent.lua"]:2805: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2646: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3159: in function <Interface/FrameXML/UIParent.lua:3138>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2078: in function <Interface/FrameXML/UIParent.lua:1362>

Locals:
shouldReloadUI = false
oldWindowsDisabled = false
oldBagsDisabled = true
oldButtonsDisabled = true
oldObjectivesDisabled = true
(*temporary) = <table> {
 dragAltKeyEnabled = false
 frameDragIsLocked = false
 scaleAltKeyEnabled = false
 scaleShiftKeyEnabled = false
 windowsDisabled = false
 objectivesDisabled = true
 scaleCtrlKeyEnabled = false
 buttonsDisabled = true
 dragCtrlKeyEnabled = false
 dragShiftKeyEnabled = false
 miscellaneousDisabled = true
 frameScaleIsLocked = false
 bagsDisabled = true
 minimapDisabled = true
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'objectivesEnabledCheckbox' (a nil value)"
DriftOptionsPanel = <table> {
 optionspanel = DriftOptionsPanel {
 }
 config = <table> {
 }
}
isRetail = true

**Comment by jaredbwasserman** [comment]
Thanks for the bug report. I am not able to repro this issue, unfortunately. Can you provide more detail on which interaction(s) with Dragonriding Customization cause this to happen? Is it the frame that lets you pick Dragonriding talents?

**Comment by class2u** [comment]
I'm sorry for misleading you. It is the system to change appearance of Dragonriding's dragon. When I enter the full screen control of appearance I got the Lua error. But everything works fine to change the appearance.

**Comment by jaredbwasserman** [comment]
Also, just double checking, what version of Drift are you running?

**Comment by class2u** [comment]
Sorry for the late reply. The Lua error is gone. With or without other addons loaded. I do not know why. Thanks for your time.
