### ISSUE TITLE
Doesn't work with Pet Scree

### ISSUE THREAD

**Issue by bjmorden** [jaredbwasserman/drift#48]
When you click on the pet screen, the screen is broken.

**Comment by jaredbwasserman** [comment]
Can you let me know which version of the game this occurs in (classic, wrath classic, or retail)? Also, can you provide a screenshot to help me understand which screen you are referring to? Thanks!

**Comment by bjmorden** [comment]
Apologies for the lack of information. 

This is on Retails.

It appears to break add-ons that use the Petpanel  For instance I tied Niggles: Pet Teams and your addon breaks Niggles.  I then tried Rematch and your addon breaks rematch as well.

**Niggles Issues**


**Rematch Issues**
![image](https://user-images.githubusercontent.com/63409087/212781880-c2458a26-481e-4b99-89d6-a5af398ed552.png)

**Comment by jaredbwasserman** [comment]
Ah interesting, thank you for the detail.

**Comment by jaredbwasserman** [comment]
I just tried both Niggles and Rematch, and they both work OK for me. Do you happen to have any other addons installed that may be interfering?

Niggles
![Niggles](https://user-images.githubusercontent.com/5832654/212828680-419fff33-9bf5-4ba0-a2cf-994fba63f4ce.PNG)

Rematch
![Rematch](https://user-images.githubusercontent.com/5832654/212828703-ce8d2c98-92df-4675-a7ab-2211d49dfc29.PNG)

**Comment by jaredbwasserman** [comment]
Oh nevermind on Niggles, I see how it's broken.

**Comment by jaredbwasserman** [comment]
I have an idea of what is causing this. It looks like Drift is overriding the Frame Strata for both of these addons to MEDIUM when by default they are HIGH. I'll need to investigate a bit more.

**Comment by jaredbwasserman** [comment]
Fixed in Drift v2.2.2.
