### ISSUE TITLE
Add slash command to reset frames

### ISSUE THREAD

**Issue by fireymerlin** [jaredbwasserman/Drift#5]
Would like a slash command to reset the frames.
This would let me make a macro or ldb to reset them.

**Comment by jaredbwasserman** [comment]
Hi @fireymerlin - thanks for the suggestion! I agree a slash command to reset the frames would be super useful. I will add it in soon.

**Comment by jaredbwasserman** [comment]
I just released a new version of Drift. Please use the slash command "/driftreset" to reset the frames. Thanks!
