### ISSUE TITLE
Interfering with Leatrix Maps

### ISSUE THREAD

**Issue by fleps** [jaredbwasserman/drift#52]
Hey there

I use Leatrix Maps - which controls its own map frame and also unlocks it for movement - but sadly your addon conflicts with it.
There isn't any error but what happens is that your addon is preventing Leatrix Maps to remember its location when I move it. It will always open again on the position where I left the default map with your addon.

I tried disabling Leatrix own movement feature but then your addon can't move it.
Could you maybe detect if Leatrix Maps is enabled and then blacklist Map frame movement/control?

Thanks

**Comment by jaredbwasserman** [comment]
Thanks for letting me know. I can look into it.

**Comment by jaredbwasserman** [comment]
Hi @fleps - I can reproduce the issue where when both addons are enabled (and Leatrix Maps has map movement toggled on), the map always opens back up in the same spot. However, I cannot reproduce the issue where disabling Leatrix Maps movement prevents Drift from moving the map. In other words, I can move the map using Drift if I disable that feature in Leatrix Maps.

Which settings are you using for Leatrix Maps? Here are mine:

![WoWScrnShot_020823_224854](https://user-images.githubusercontent.com/5832654/217739322-3da27ddd-587e-4826-874b-35af7e62988e.jpg)

**Comment by fleps** [comment]
Hi @jaredbwasserman 

I had the Unlock map frame enabled and only tested with the sub-config regarding map movement disabled.
I tested now with the unlock map frame unchecked and indeed it works without issue.
Thanks for checking this, I believe the issue can be closed then.
