### ISSUE TITLE
Dressing Room Resize Not Working

### ISSUE THREAD

**Issue by webdevdave** [jaredbwasserman/drift#57]
When I right click on the Dressing Room window and try to resize it via Right-Click and Drag, nothing seems to happen. I am using ElvUI, but I don't think that is the problem because other windows work fine. So just wanted to bring it to your attention.

Thanks and love the addon (still)... it's one of my favorites!

**Comment by jaredbwasserman** [comment]
Thanks for letting me know. I will take a look.

**Comment by jaredbwasserman** [comment]
Hmm I cannot reproduce the issue (I just tested with and without ElvUI). Do you have any other addons installed that may be interfering? And just double checking what version of the game are you running?

**Comment by webdevdave** [comment]
So, I figured out that when I have the "Resize Window" checkbox enabled, in the addon [Better Wardrobe](https://www.curseforge.com/wow/addons/better-wardrobe-and-transmog), that is what is causing the issue. So, I unchecked that and it seems to be working better. Thanks!

**Comment by jaredbwasserman** [comment]
Thanks for the info!
