### ISSUE TITLE
Classic WotLK - Dressing room not working properly when auction house is open 

### ISSUE THREAD

**Issue by cbcatanz** [jaredbwasserman/drift#59]
I've noticed the dressing room is working properly when the auction house is open with this addon active. 
I will control click on an item in the AH, the dressing room will display properly, but if I close the dressing room and the AH, then reopen the AH and control click an item the dressing room will not display correctly. The reset button is blank and you can't move your character from side to side. 
If I disable the Drift addons the dressing room w/AH open work perfectly fine.

**Comment by jaredbwasserman** [comment]
Thanks for letting me know.

**Comment by jaredbwasserman** [comment]
I have an idea of what is causing this issue. Can you test with this attached version of Drift and let me know if the issue still shows up?

[drift-v2.2.12-wc.zip](https://github.com/jaredbwasserman/drift/files/12865338/drift-v2.2.12-wc.zip)

**Comment by cbcatanz** [comment]
I've got to start work pretty soon. I'll give it a try later today and report back.

**Comment by cbcatanz** [comment]
The issue seems to be fixed using the newer version you linked.

**Comment by jaredbwasserman** [comment]
Fixed in v2.2.13.
