### ISSUE TITLE
Suggestion, Check boxes

### ISSUE THREAD

**Issue by Partywagon89** [jaredbwasserman/Drift#6]
Enable/Disable options would be nice for JUST Dragging window and/or resizing not both :)

**Comment by jaredbwasserman** [comment]
Hi @Partywagon89 - thanks for your suggestion!  I agree it would be useful to be able to independently enable/disable dragging and resizing.  I'll consider adding this in the future.

**Comment by jaredbwasserman** [comment]
Hi @Partywagon89 - I added independent enable/disable options for moving and scaling, respectively, in the most recent version of Drift. Please download the latest version and go to Game Menu -> Interface -> AddOns -> Drift -> Options to access the new options!
