### ISSUE TITLE
bug InterfaceOptions_AddCategory

### ISSUE THREAD

**Issue by Addonman** [jaredbwasserman/drift#65]
Message: Interface/AddOns/Drift/DriftOptions.lua line 95:
   attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
Debug:
   [string "@Interface/AddOns/Drift/DriftOptions.lua"]:95: SetupConfig()
   [string "@Interface/AddOns/Drift/Drift.lua"]:530:
      Interface/AddOns/Drift/Drift.lua:525

**Comment by devwrk** [comment]
look at issue #64, there are solutions to fix this

**Comment by jaredbwasserman** [comment]
I am going to close this in favor of https://github.com/jaredbwasserman/drift/issues/64
