### ISSUE TITLE
Drift won't load after the 11.0.2 update

### ISSUE THREAD

**Issue by JyanseiCoding** [jaredbwasserman/drift#69]
Found this lua error in Bugsack

> 1x Drift/DriftOptions.lua:367: attempt to call global 'GetAddOnMetadata' (a nil value)
> [string "@Drift/DriftOptions.lua"]:367: in function `SetupConfig'
> [string "@Drift/Drift.lua"]:536: in function <Drift/Drift.lua:531>
> 
> Locals:
> self = <table> {
>  waitTable = <table> {
>  }
>  resetTable = <table> {
>  }
> }
> driftOptionsTitle = FontString {
> }
> lockMoveTitle = FontString {
> }
> yOffset = -230
> lockScaleTitle = FontString {
> }
> frameToggleTitle = FontString {
> }
> driftOptionsVersionLabel = FontString {
> }
> driftOptionsVersionContent = FontString {
> }
> (*temporary) = FontString {
> }
> (*temporary) = nil
> (*temporary) = "Drift"
> (*temporary) = "Version"
> (*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"
> DriftOptionsPanel = <table> {
>  optionspanel = DriftOptionsPanel {
>  }
>  config = <table> {
>  }
> }
> isRetail = true

**Comment by Aur0r4** [comment]
+1

**Comment by jaredbwasserman** [comment]
Thanks, looking...

**Comment by jaredbwasserman** [comment]
Fixed in v2.3.1.
