### ISSUE TITLE
/driftreset not resetting the frames

### ISSUE THREAD

**Issue by WybeBosch** [jaredbwasserman/Drift#7]
hey there! 
In an attempt to fix another issue i came across i attempted to reset all frames saved position
by typing `/driftreset` however when i do that WoW does not recognize the command (And i made sure the addon was loaded)
I also attempted `/drift reset` but neither worked. Is this something that is temporarly broken? or is named a different command? :)

**Comment by WybeBosch** [comment]
Opening Escape>Interface>Drift>General options>BUTTON: Reset Frames
Does allow me to press the button to reset the frames, so its not the worst thing in the world :D Was just wondering why the commandline wasnt working.

**Comment by jaredbwasserman** [comment]
Hi Wybe, thanks for letting me know about the issue! I have a couple questions to help narrow down the cause.

1) What version of Drift do you have installed? The `/driftreset` command was just added in the most recent version of the addon (1.0.4). If you have anything older installed, the command does not exist. You can check the version by doing Escape->Interface->AddOns->Drift and seeing what number is next to "Version".

2) Is the issue that WoW says `Type /help for a listing of a few commands.` after you enter `/driftreset`? Or is the issue that you enter `/driftreset` but nothing happens? I want to make sure I understand.

Also, I'm planning to add `/drift reset` in the future, but it's not implemented  yet.

-Jared

**Comment by WybeBosch** [comment]
Oof, i did indeed not check if i had the latest version installed. Sorry that i forgot one of the most basic troubleshooting steps besides turning it on and off again haha!

I had version 1.03 installed, just installed the latest 1.04 and the chat command is now correctly working!! :) 
Issue can be closed!
